vaults:
- psap-forge-ci


cluster:
  name: totor
ci_job:
  name: hello
  project: llmd
  args: []

fournos:
  namespace: psap-automation
  kubeconfig:
    vault:
      name: psap-forge-ci
      key: kubeconfig
