vaults:
- psap-forge-ci

cluster:
  name: null
ci_job:
  name: null
  project: null
  args: []

overrides: {} # don't touch this one directly, the config module will populate it
extra_overrides: {}

fournos:
  namespace: psap-automation
  kubeconfig:
    vault:
      name: psap-forge-ci
      key: kubeconfig
  job:
    owner: "FORGE/fournos-launcher"
    display_name: "Forge Job"
    pipeline_name: forge-test-only
    env:
      OPENSHIFT_CI_job: [JOB_TYPE, JOB_NAME, JOB_SPEC, OPENSHIFT_CI, JOB_NAME_SAFE, BUILD_ID]
      OPENSHIFT_CI_git_pr: [PULL_PULL_SHA, PULL_NUMBER, PULL_BASE_REF, REPO_NAME, REPO_OWNER, PULL_BASE_SHA, JOB_NAME, PULL_TITLE, PULL_REFS, PULL_HEAD_REF]
