kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  namespace: ci
  name: forge-light
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 2
  output:
    pushSecret:
      name: registry-push-credentials-ci-images-mirror
    to:
      kind: DockerImage
      name: quay.io/openshift/ci:ci_forge-light_latest
  source:
    dockerfile: |
      # INCLUDE HERE
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: quay.io/centos/centos:stream10
      imageOptimizationPolicy: SkipLayers
    type: Docker
  triggers:
  - type: ConfigChange
